## Redes Neurais Artificiais 2020.1

**Disciplina**: Redes Neurais Artificiais 2020.1  
**Professora**: Elloá B. Guedes (ebgcosta@uea.edu.br)  
**Github**: http://github.com/elloa  

### Alunos

Leonardo Monteiro Neres de Lima - 1615080320 (lmndl.eng16@uea.edu.br) <br>
Thatielen Oliveira Pereira - 1515080618 (top.eng@uea.edu.br) <br>
Vyctor Lima Negreiros - 1615080372 (vln.eng16@uea.edu.br) <br>

Levando em conta a base de dados **_Forest Cover Type_**, esta terceira parte do Projeto Prático 3 diz respeito à proposição e avaliação de múltiplas redes neurais artificiais do tipo feedforward multilayer perceptron para o problema da classificação multi-classe da cobertura florestal em uma área do Roosevelt National Forest.

## Testando Redes Neurais sem os Atributos Categórios

1. Abra a base de dados em questão
2. Elimine todas as colunas relativas aos atributos categóricos
3. Armazene o atributo alvo em uma variável y e os atributos preditores em uma variável X
4. Efetue uma partição holdout 70/30 com o sklearn, distribuindo os exemplos de maneira aleatória
5. Efetue o escalonamento dos atributos

### Escalonando os atributos

O treinamento de uma rede neural artificial é mais eficiente quando os valores que lhes são fornecidos como entrada são pequenos, pois isto favorece a convergência. Isto é feito escalonando-se todos os atributos para o intervalo [0,1], mas precisa ser feito de maneira cautelosa, para que informações do conjunto de teste não sejam fornecidas no treinamento.

Há duas estratégias para tal escalonamento: normalização e padronização. Ambas possuem características particulares, vantagens e limitações, como é possível ver aqui: https://www.analyticsvidhya.com/blog/2020/04/feature-scaling-machine-learning-normalization-standardization/


No nosso caso, vamos usar a padronização. Assim, com os atributos preditores do treinamento, isto é, X_train, deve-se subtrair a média e dividir pelo desvio padrão:

X_train_std = (X_train - np.mean(X_train))/np.std(X_train)

Em seguida, o mesmo deve ser feito com os atributos preditores do conjunto de testes, mas com padronização relativa ao conjunto de treinamento:

X_test_std = (X_test - np.mean(X_train))/np.std(X_train)

Se todo o conjunto X for utilizado na padronização, a rede neural receberá informações do conjunto de teste por meio da média e variância utilizada para preparar os dados de treinamento, o que não é desejável.


### Continuando

5. Treine uma rede neural multilayer perceptron para este problema com uma única camada e dez neurônios  
    5.1 Utilize a função de ativação ReLU  
    5.2 Utilize o solver Adam    
    5.3 Imprima o passo a passo do treinamento    
    5.4 Utilize o número máximo de épocas igual a 300  
6. Com o modelo em questão, após o treinamento, apresente:  
    6.1 Matriz de confusão para o conjunto de teste  
    6.2 Acurácia  
    6.3 F-Score  
    6.4 Precisão  
    6.5 Revocação  
7. Repita o treinamento da mesma rede anterior sem imprimir o passo a passo (verbose False) por 100 vezes  
    7.1 Cada uma destas repetições deve ser feita com uma nova partição Holdout  
    7.2 Apresente a média e o desvio padrão da acurácia e do F-Score para o conjunto de treino  
8. Repita por 100 vezes o treinamento desta mesma rede, mas utilizando o otimizador SGD  
    8.1 Apresente a média e o desvio padrão da acurácia e do F-Score para o conjunto de treino  
9. Houve influência da escolha do otimizador no desempenho da rede?

In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, os
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score 

## Testando Redes Neurais sem os Atributos Categórios

### Testando Redes Neurais sem os Atributos Categórios

### 1. Abra a base de dados em questão

In [ ]:
data = pd.read_csv('../datasets/covtype.csv', sep=";")

In [2]:
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv('/content/drive/My Drive/datasets/covtype.csv', sep=";")

Mounted at /content/drive


### 2. Elimine todas as colunas relativas aos atributos categóricos

In [3]:
patterns = ['Soil_Type', 'Wilderness_Area']
categorical_columns = [column for column in data.columns if not any(pattern in column for pattern in patterns)]

data = data[categorical_columns]

In [4]:
print(data.columns.to_list())

['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Cover_Type']


### 3. Armazene o atributo alvo em uma variável y e os atributos preditores em uma variável X

In [5]:
X, Y = data[data.columns.drop('Cover_Type')], data['Cover_Type']

### 4. Efetue uma partição holdout 70/30 com o sklearn, distribuindo os exemplos de maneira aleatória

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, shuffle=True)

### 5. Efetue o escalonamento dos atributos

In [8]:
X_train_std = (X_train - np.mean(X_train)) / np.std(X_train)
X_test_std = (X_test - np.mean(X_train)) / np.std(X_train)

### 5. Treine uma rede neural multilayer perceptron para este problema com uma única camada e dez neurônios

**5.1 Utilize a função de ativação ReLU**<br>
**5.2 Utilize o solver Adam**<br>
**5.3 Imprima o passo a passo do treinamento**<br>
**5.4 Utilize o número máximo de épocas igual a 300**

In [ ]:
perceptron = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', solver='adam', verbose=True, max_iter=300)

In [ ]:
perceptron.fit(X_train_std, Y_train);

Iteration 1, loss = 0.90057005
Iteration 2, loss = 0.71023686
Iteration 3, loss = 0.68932878
Iteration 4, loss = 0.68048000
Iteration 5, loss = 0.67511948
Iteration 6, loss = 0.67117152
Iteration 7, loss = 0.66887583
Iteration 8, loss = 0.66703407
Iteration 9, loss = 0.66537890
Iteration 10, loss = 0.66365219
Iteration 11, loss = 0.66213481
Iteration 12, loss = 0.66125390
Iteration 13, loss = 0.66058511
Iteration 14, loss = 0.66005505
Iteration 15, loss = 0.65957553
Iteration 16, loss = 0.65922977
Iteration 17, loss = 0.65886395
Iteration 18, loss = 0.65836718
Iteration 19, loss = 0.65792777
Iteration 20, loss = 0.65745198
Iteration 21, loss = 0.65720102
Iteration 22, loss = 0.65686246
Iteration 23, loss = 0.65662604
Iteration 24, loss = 0.65636932
Iteration 25, loss = 0.65620250
Iteration 26, loss = 0.65612268
Iteration 27, loss = 0.65599110
Iteration 28, loss = 0.65585932
Iteration 29, loss = 0.65581536
Iteration 30, loss = 0.65570859
Iteration 31, loss = 0.65569859
Iteration 32, los

### 6. Com o modelo em questão, após o treinamento, apresente:

**6.1 Matriz de confusão para o conjunto de teste**

In [ ]:
Y_pred_test = perceptron.predict(X_test_std)

cm_test = confusion_matrix(Y_test, Y_pred_test)

In [ ]:
print(cm_test)

[[44972 17242     7     0    10    13  1045]
 [15596 67914  1147     0   115   567     8]
 [    0  1826  7635   235     0  1041     0]
 [    0     8   413   285     0   110     0]
 [    8  2538    35     0   222    38     0]
 [    0  1442  2227    69     0  1438     0]
 [ 3603    34     0     0     0     0  2461]]


**6.2 Acurácia**

In [ ]:
accuracy = accuracy_score(Y_test, Y_pred_test)
print(accuracy)

0.7167190655406646


**6.3 F-Score**

In [ ]:
f_score = f1_score(Y_test, Y_pred_test, average='macro')
print(f_score)

0.5091072540805867


**6.4 Precisão**

In [ ]:
precision = precision_score(Y_test, Y_pred_test, average='macro')
print(precision)

0.6264823567208927


**6.5 Revocação**

In [ ]:
recall = recall_score(Y_test, Y_pred_test, average='macro')
print(recall)

0.47517367219020856


### Repita o treinamento da mesma rede anterior sem imprimir o passo a passo (verbose False) por 100 vezes

**7.1 Cada uma destas repetições deve ser feita com uma nova partição Holdout**<br>
**7.2 Apresente a média e o desvio padrão da acurácia e do F-Score para o conjunto de treino**

In [ ]:
accuracies, f_scores = [], []

for i in range(100):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, shuffle=True)
    
    X_train_std = (X_train - np.mean(X_train)) / np.std(X_train)
    X_test_std = (X_test - np.mean(X_train)) / np.std(X_train)
    
    perceptron = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', solver='adam', max_iter=300)
    perceptron.fit(X_train_std, Y_train)
    
    Y_pred_train = perceptron.predict(X_train_std)
        
    accuracy = accuracy_score(Y_train, Y_pred_train)
    accuracies.append(accuracy)
    
    f_score = f1_score(Y_train, Y_pred_train, average='macro')
    f_scores.append(f_score)

In [ ]:
print("Acurácia Média: %.4f" % np.mean(accuracies))
print("Desvio Padrão Acurácia: %.4f" % np.std(accuracies))

Acurácia Média: 0.7181
Desvio Padrão Acurácia: 0.0030


In [ ]:
print("F-Score Médio: %.4f" % np.mean(f_scores))
print("Desvio Padrão F-Score: %.4f" % np.std(f_scores))

F-Score Médio: 0.5158
Desvio Padrão F-Score: 0.0198


### Repita por 100 vezes o treinamento desta mesma rede, mas utilizando o otimizador SGD
**8.1 Apresente a média e o desvio padrão da acurácia e do F-Score para o conjunto de treino**

In [ ]:
accuracies, f_scores = [], []

for i in range(100):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, shuffle=True)
    
    X_train_std = (X_train - np.mean(X_train)) / np.std(X_train)
    X_test_std = (X_test - np.mean(X_train)) / np.std(X_train)
    
    perceptron = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', solver='sgd', max_iter=300)
    perceptron.fit(X_train_std, Y_train)
    
    Y_pred_train = perceptron.predict(X_train_std)
        
    accuracy = accuracy_score(Y_train, Y_pred_train)
    accuracies.append(accuracy)
    
    f_score = f1_score(Y_train, Y_pred_train, average='macro')
    f_scores.append(f_score)

In [ ]:
print("Acurácia Média: %.4f" % np.mean(accuracies))
print("Desvio Padrão Acurácia: %.4f" % np.std(accuracies))

Acurácia Média: 0.7148
Desvio Padrão Acurácia: 0.0028


In [ ]:
print("F-Score Médio: %.4f" % np.mean(f_scores))
print("Desvio Padrão F-Score: %.4f" % np.std(f_scores))

F-Score Médio: 0.4807
Desvio Padrão F-Score: 0.0170


**9. Houve influência da escolha do otimizador no desempenho da rede?**

Como pode ser observado, não houve perda significativa de acuáricia, havendo apenas uma leve diminuição no F-Score obtido para a rede treinada com o otimizador SGD. Também foi possível perceber uma melhora no tempo necessário para convergência, quando utilizado este mesmo otimizador, resultando em um tempo de treinamento menor ao do primeiro otimizador.

## Discussão

Nos passos anteriores, você avaliou o desempenho de uma única rede neural que contém os seguintes parâmetros: uma única camada oculta com 10 neurônios e função de ativação ReLU. O otimizador utilizado, quer seja SGD ou ADAM, trata-se do algoritmo para aproximar o gradiente do erro. Neste sentido, a escolha do otimizador é um hiperparâmetro, pois diz respeito a como a rede neural definida previamente atuará "em tempo de execução"  durante o processo de treinamento. Também são hiperparâmetros a quantidade de épocas, a taxa de aprendizado inicial, dentre outros.

Cabe alientar também que você efetuou o treinamento desta rede por 100 vezes e apresentou os resultados em termos de média +- desvio padrão. Lembre-se que em uma rede neural há a inicialização aleatória de pesos e, em consequência, o desempenho delas está sujeito à uma flutuação estocástica. A execução destas múltiplas vezes faz com que eliminemos algum viés introduzido por uma boa ou má "sorte" na escolha de pesos no caso de uma única execução.

Você também aprendeu uma estratégia para escalonar os atributos para uma melhor convergência da rede. Utilize-a em todos os treinamentos e testes propostos a seguir.

## Propondo Novas Arquiteturas

Variando  os parâmetros (uma ou duas camadas ocultas, com diferente números de neurônios em cada uma delas e a função de ativação) e o hiperparâmetros solver (Adam ou SGD) e o número de épocas (100,150 e 200), atenda ao que se pede:

1. Proponha 10 arquiteturas distintas de RNAs para o problema em questão, à sua escolha
2. Avalie cada uma das arquiteturas perante todos os hiperparâmetros apresentados por 100 vezes
3. Como resultado da avaliação, apresente:  
    3.1 Top-3 melhores redes no tocante à F-Score e Acurácia  
    3.2 Repetição em que houve o melhor desempenho de cada uma dessas redes: ilustre tp, tf, fp e fn  

**1. Proponha 10 arquiteturas distintas de RNAs para o problema em questão, à sua escolha**

In [7]:
models = [
          MLPClassifier(hidden_layer_sizes=(10, 8), activation='relu', solver='adam', max_iter=100), 
          MLPClassifier(hidden_layer_sizes=(10, 10), activation='identity', solver='sgd', max_iter=150),
          MLPClassifier(hidden_layer_sizes=(8, 8), activation='relu', solver='adam', max_iter=200),
          MLPClassifier(hidden_layer_sizes=(6, 6), activation='identity', solver='sgd', max_iter=100),
          MLPClassifier(hidden_layer_sizes=(10, 6), activation='relu', solver='adam', max_iter=150),
          MLPClassifier(hidden_layer_sizes=(20, 10), activation='identity', solver='sgd', max_iter=200),
          MLPClassifier(hidden_layer_sizes=(20, 10), activation='relu', solver='adam', max_iter=200),
          MLPClassifier(hidden_layer_sizes=(20, 20), activation='relu', solver='sgd', max_iter=150),
          MLPClassifier(hidden_layer_sizes=(10, 5), activation='relu', solver='adam', max_iter=100),
          MLPClassifier(hidden_layer_sizes=(10, 5), activation='identity', solver='sgd', max_iter=100),
          ]

**2. Avalie cada uma das arquiteturas perante todos os hiperparâmetros apresentados por 100 vezes**

In [ ]:
accuracies, f_scores, confusions_matrix = [], [], []
for i in models:
  accuracies.append([])
  f_scores.append([])
  confusions_matrix.append([])

for i in range(len(models)):
  print(i)
  for j in range(100):
      X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, shuffle=True)
      
      X_train_std = (X_train - np.mean(X_train)) / np.std(X_train)
      X_test_std = (X_test - np.mean(X_train)) / np.std(X_train)
      
      perceptron = models[i]
      perceptron.fit(X_train_std, Y_train)
      
      Y_pred_train = perceptron.predict(X_train_std)
          
      accuracy = accuracy_score(Y_train, Y_pred_train)
      accuracies[i].append(accuracy)
      
      f_score = f1_score(Y_train, Y_pred_train, average='macro')
      f_scores[i].append(f_score)

      Y_pred_test = perceptron.predict(X_test_std)
      cm_test = confusion_matrix(Y_test, Y_pred_test)
      confusions_matrix[i].append(cm_test)

0


**3. Como resultado da avaliação, apresente:**

**3.1 Top-3 melhores redes no tocante à F-Score e Acurácia**

In [73]:
def print_model(model):
  print("hidden_layer_sizes: "+str(model.hidden_layer_sizes)+", activation: "+
        str(model.activation)+", solver: "+str(model.solver)+
        ", max_iter: "+str(model.max_iter))

# Top 3 em relacao a acuracia
accuracies_sum = []
for i in range(len(models)):
  accuracies_sum.append(sum(accuracies[i]))

models_sort = np.argsort(accuracies_sum)

print("-----Top 3 em relação à acurácia-----")
for i in range(3):
  print(str(i+1)+'º Lugar: ')
  index = models_sort[-3:][2-i]
  print_model(models[index])
  print("Acurácia Média: %.4f" % np.mean(accuracies[index]))
  print("Desvio Padrão Acurácia: %.4f" % np.std(accuracies[index]))
  print()

# Top 3 em relacao ao F-score
f_scores_sum = []
for i in range(len(models)):
  f_scores_sum.append(sum(f_scores[i]))

models_sort = np.argsort(f_scores_sum)

print("\n-----Top 3 em relação ao F-score-----")
for i in range(3):
  print(str(i+1)+'º Lugar: ')
  index = models_sort[-3:][2-i]
  print_model(models[index])
  print("F-Score Média: %.4f" % np.mean(f_scores[index]))
  print("Desvio Padrão F-Score: %.4f" % np.std(f_scores[index]))
  print()

-----Top 3 em relação à acurácia-----
1º Lugar: 
hidden_layer_sizes: (20, 20), activation: relu, solver: sgd, max_iter: 150
Acurácia Média: 0.7603
Desvio Padrão Acurácia: 0.0041

2º Lugar: 
hidden_layer_sizes: (20, 10), activation: relu, solver: adam, max_iter: 200
Acurácia Média: 0.7582
Desvio Padrão Acurácia: 0.0024

3º Lugar: 
hidden_layer_sizes: (8, 8), activation: relu, solver: adam, max_iter: 200
Acurácia Média: 0.7275
Desvio Padrão Acurácia: 0.0010


-----Top 3 em relação ao F-score-----
1º Lugar: 
hidden_layer_sizes: (20, 10), activation: relu, solver: adam, max_iter: 200
F-Score Média: 0.6033
Desvio Padrão F-Score: 0.0142

2º Lugar: 
hidden_layer_sizes: (20, 20), activation: relu, solver: sgd, max_iter: 150
F-Score Média: 0.5893
Desvio Padrão F-Score: 0.0139

3º Lugar: 
hidden_layer_sizes: (10, 8), activation: relu, solver: adam, max_iter: 100
F-Score Média: 0.5483
Desvio Padrão F-Score: 0.0082



**3.2 Repetição em que houve o melhor desempenho de cada uma dessas redes: ilustre tp, tf, fp e fn**

In [92]:
for i in range(len(models)):
  index = accuracies[i].index(max(accuracies[i]))
  cm = confusions_matrix[i][index]

  FP = cm.sum(axis=0) - np.diag(cm)
  FN = cm.sum(axis=1) - np.diag(cm)
  TP = np.diag(cm)
  TN = cm.sum() - (FP + FN + TP)

  print_model(models[i])
  print("FP: " + str(FP))
  print("FN: " + str(FN))
  print("TP: " + str(TP))
  print("TN: " + str(TN))
  print()

hidden_layer_sizes: (10, 8), activation: relu, solver: adam, max_iter: 100
FP: [15690 25504  3724   387    37  1300   791]
FN: [20557 14568  2661   347  2568  3868  2864]
TP: [43188 70242  8061   434   199  1402  3345]
TN: [ 94869  63990 159858 173136 171500 167734 167304]

hidden_layer_sizes: (10, 10), activation: identity, solver: sgd, max_iter: 150
FP: [20609 25095  5056   100     0   547  1349]
FN: [19568 17671  2630   686  2882  4959  4360]
TP: [44236 66984  8082   126     0   404  1716]
TN: [ 89891  64554 158536 173392 171422 168394 166879]

hidden_layer_sizes: (8, 8), activation: relu, solver: adam, max_iter: 200
FP: [17380 23596  4339   121   174  1123   863]
FN: [18734 16234  2560   656  2496  4220  2696]
TP: [44757 68730  8275   181   324   999  3442]
TN: [ 93433  65744 159130 173346 171310 167962 167303]

hidden_layer_sizes: (6, 6), activation: identity, solver: sgd, max_iter: 100
FP: [20994 24479  4981   112     0   772  1162]
FN: [18957 18156  2760   777  2819  4664  4367]

## Estimando o número de neurônios

Um dos problemas de pesquisa com redes neurais artificiais consiste na determinação do número de neurônios em sua arquitetura. Embora não seja possível definir a priori qual rede neural é adequada para um problema, pois isto só é possível mediante uma busca exaustiva, há regras na literatura que sugerem o número de neurônios escondidos, tal como a regra da Pirâmide Geométrica, dada a seguir:

$$N_h = \alpha \cdot \sqrt{N_i \cdot N_o},$$

em que $N_h$ é o número de neurônios ocultos (a serem distribuídos em uma ou duas camadas ocultas), $N_i$ é o número de neurônios na camada de entrada e $N_o$ é o número de neurônios na camada de saída. 

1. Consulte a documentação da classe MLPClassifier (disponível em https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html) e obtenha os valores de $N_i$ e $N_h$.
2. Teste os valores de $\alpha$ como sendo iguais a $0.5$, $2$ e $3$.
3. Proponha pelo menos 30 redes neurais segundo a regra da pirâmide geométrica e teste-as nos mesmos termos estabelecidos anterioremente  (solver, épocas, etc.)  
    3.1 Apresente as top-3 melhores redes no tocante à F-Score e Acurácia  

## Testando as Redes Neurais com Atributos Categóricos

1. Considere as 6 redes neurais obtidas nos dois top-3 anteriores (arquiteturas próprias e regra da pirâmide geométrica)
2. Com todos os atributos preditores da base de dados original, incluindo os categóricos, treine e teste estas mesmas redes por 100 repetições  
    2.1 Considere o melhor otimizador para cada uma delas  
    2.2 Faça uso de 200 épocas para treinamento  
    2.2 Apresente os resultados de acurácia e F-Score em termos da média +- dp para cada arquitetura
3. Apresente o gráfico boxplot para o F-Score das 6 arquiteturas perante as 100 repetições

## Considerações Parciais

1. É possível identificar uma rede com desempenho superior às demais?
2. Qual estratégia mostrou-se mais producente para a obtenção de boas arquiteturas (Estratégia Própria ou Pirâmide Geométrica)? Por quê?
3. Considerar os atributos categóricos trouxe melhorias? Justifique.
4. Um número maior de épocas trouxe melhorias?
5. Qual a maior dificuldade de resolução do problema proposto perante as RNAs?